# Generated by Django 4.2.1 on 2023-05-24 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsportal', '0002_commentdislike_comment_disliked_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Cryptocurrency',
        ),
        migrations.AlterField(
            model_name='reklama',
            name='nuotrauka',
            field=models.ImageField(blank=True, null=True, upload_to='photos', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='reklama',
            name='papildoma_info',
            field=models.TextField(verbose_name=''),
        ),
    ]
